DELETE FROM items;

INSERT INTO items (name, description, image_filename, price, impact) VALUES
  ('USD Token',
   'A 1:1 stablecoin fully backed by U.S. dollar reserves, USD Token offers ultra-low volatility and is widely used for DeFi lending, payments, and cross-border transfers. With 24/7 liquidity pools and integrated governance, it''s the go-to choice for traders seeking a reliable dollar peg.',
   'usd.png', 1.00, 0.75),
  ('EUR Token',
   'Pegged to the euro, EUR Token delivers seamless access to European markets. It features automated reserve audits and a built-in staking mechanism that rewards holders with network fees, making it popular among businesses and remittance services.',
   'eur.png', 0.90, 0.65),
  ('JPY Token',
   'Designed for micro-transactions, JPY Token mirrors the Japanese yen and boasts sub-second settlement times with negligible fees. Its lightweight contract architecture makes it ideal for IoT payments and in-game purchases across global marketplaces.',
   'jpy.png', 110.00, 0.40),
  ('GBP Token',
   'With a sterling peg, GBP Token combines stability with DeFi yield-earning capabilities. It integrates natively into major lending protocols in the UK and supports instant merchant payouts via smart routing to lower FX slippage.',
   'gbp.png', 0.78, 0.60),
  ('INR Token',
   'INR Token brings the Indian rupee on-chain, offering enhanced access to emerging-market liquidity. It features an elastic supply model to maintain peg stability during market swings and powers cross-border payroll solutions for SMEs.',
   'inr.png', 75.00, 0.50),
  ('AUD Token',
   'Australian Dollar–pegged AUD Token features an adjustable interest mechanism that shares a portion of transaction fees back to token holders. Its green-energy offset protocol also donates a fraction of fees to environmental projects Down Under.',
   'aud.png', 1.35, 0.55),
  ('CAD Token',
   'Pegged to the Canadian dollar, CAD Token emphasizes privacy with optional shielded transactions. It''s widely accepted by North American merchants and supports atomic swaps for frictionless exchange with other major stablecoins.',
   'cad.png', 1.25, 0.52),
  ('CNY Token',
   'A digital representation of the Chinese yuan, CNY Token leverages high-throughput Layer-2 scaling for retail and institutional users. It includes a dual-reserve model combining on-chain collateral and off-chain sovereign bonds.',
   'cny.png', 6.45, 0.45),
  ('BRL Token',
   'Brazil-pegged BRL Token empowers Latin American remittances with ultra-competitive fees. Its dynamic collateralization system automatically adjusts to local liquidity conditions, ensuring peg stability during volatile markets.',
   'brl.png', 5.20, 0.60),
  ('ZAR Token',
   'The South African rand''s on-chain counterpart, ZAR Token, targets underbanked regions with low-cost mobile wallet integration. Its community governance council allocates a share of network fees to local economic development initiatives.',
   'zar.png', 14.80, 0.58);
